version: "3.9"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ferdb
      MYSQL_ROOT_PASSWORD: 3k5C3ubr
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
  web:
    restart: always
    environment:
        MYSQL_HOST: db
        MYSQL_PORT: 3306
        MYSQL_USER: ponciks
        MYSQL_DATABASE: ferdb
        MYSQL_PASSWORD: 3k5C3ubr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - db